## Vertex AI Model Garden
##  - model repository both google as well as open source
## Vertex AI Moel Builder
## Vertex AI Agent Builder
##  - search, recommendation, agents (LLM based chatbot)
##  - generic, media, retail, healthcare

## how to improve LLM performance
##  - prompt design - art and science of figuring out what text to feed your language model to get it to take on the behavior you want.
##  - decoding strategies / prompt tuning (change model parameter eg. temperature (degree of randomless), top k, top p
##  - grouding and RAG (eg vertex ai vector search): answering not just by what LLM has but querying external systems
##  - tuning - training with specific data set, Paramemter-Efficient Fine Tuning methods (PEFT)

## Hallucinations refer to instances where the AI model generates content that is unrealistic, fictional, or completely fabricated.
## Factuality relates to the accuracy or truthfulness of the information generated by a generative AI model.
## Anthropomorphization refers to the attribution of human-like qualities, characteristics, or behaviors to non-human entities, such as machines or AI models.
